apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/your-org/e7012e-roof-control-hub
    newName: ghcr.io/your-org/e7012e-roof-control-hub
    newTag: latest
