apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: e7012e-roof

resources:
  - namespace.yaml
  - roof-control-hub/deployment.yaml
  - roof-control-hub/service.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/prometheus-service.yaml
  - monitoring/grafana-admin-secret.yaml
  - monitoring/grafana-datasource-config.yaml
  - monitoring/grafana-deployment.yaml
  - monitoring/grafana-service.yaml
  - ingress.yaml
